// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonManagementApp.Data.Data;

#nullable disable

namespace PersonManagementApp.Data.Migrations
{
    [DbContext(typeof(PersonManageAppDbContext))]
    [Migration("20240805084732_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PersonManagementApp.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressOfPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressOfPersonId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressOfPersonId = 2,
                            Name = "Hà Nội",
                            Number = 30
                        },
                        new
                        {
                            Id = 2,
                            AddressOfPersonId = 1,
                            Name = "Hà Tĩnh",
                            Number = 38
                        },
                        new
                        {
                            Id = 3,
                            AddressOfPersonId = 3,
                            Name = "Quảng Bình",
                            Number = 73
                        },
                        new
                        {
                            Id = 4,
                            AddressOfPersonId = 4,
                            Name = "Nghệ An",
                            Number = 37
                        });
                });

            modelBuilder.Entity("PersonManagementApp.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("PersonManagementApp.Data.Models.Professor", b =>
                {
                    b.HasBaseType("PersonManagementApp.Data.Models.Person");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Professor");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            EmailAddress = "professor.a@example.com",
                            FullName = "Nguyễn Thanh Bình",
                            PhoneNumber = "0343689648",
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = 4,
                            EmailAddress = "professor.bb@example.com",
                            FullName = "Trần Văn Dương",
                            PhoneNumber = "0969483658",
                            Salary = 100000.0
                        });
                });

            modelBuilder.Entity("PersonManagementApp.Data.Models.Student", b =>
                {
                    b.HasBaseType("PersonManagementApp.Data.Models.Person");

                    b.Property<double>("AverageMark")
                        .HasColumnType("float");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "student.a@example.com",
                            FullName = "Lê Công Thành",
                            PhoneNumber = "0834361811",
                            AverageMark = 85.5,
                            StudentNumber = "000001"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "student.bb@example.com",
                            FullName = "Nguyễn Văn A",
                            PhoneNumber = "0747657485",
                            AverageMark = 75.5,
                            StudentNumber = "000002"
                        });
                });

            modelBuilder.Entity("PersonManagementApp.Data.Models.Address", b =>
                {
                    b.HasOne("PersonManagementApp.Data.Models.Person", "Person")
                        .WithOne("Address")
                        .HasForeignKey("PersonManagementApp.Data.Models.Address", "AddressOfPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonManagementApp.Data.Models.Person", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
